SELECT static_subunit_info.unit_name as unit_name, static_subunit_info.subunit_name as subunit_name
FROM static_approvers_info
LEFT JOIN static_subunit_info
ON static_approvers_info.subunit_id = static_subunit_info.subunit_id
where static_approvers_info.approver_netId=:approver_netId;
